server:
  servlet:
    encoding:
      charset: utf-8
      force: true
    session:
      timeout: 30m
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: never
      data-locations:
        - classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false

portone:
    imp-key: ${IMP_REST_API_KEY}
    imp-secret: ${IMP_SECRET_KEY}

solapi:
    api-key: ${SOLAPI_API_KEY}
    api-secret: ${SOLAPI_API_SECRET}
    from: ${FROM}

app:
  base-url: ${BASE_URL:http://localhost:8080}
  upload:
    base-path: ${UPLOAD_BASE_PATH:C:/uploads/}
    notice-path: ${UPLOAD_NOTICE_PATH:C:/uploads/notice}
    notice-file-path: ${UPLOAD_NOTICE_FILE_PATH:C:/uploads/files}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true